name: Docker Build

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find ./docker -name 'Dockerfile' -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')"

  build:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: |
          dir_name=$(basename ${{ matrix.dir }})
          docker build -t "$dir_name:latest" ${{ matrix.dir }}
